ppiok-OwO/MoonRabbits

src/config/config.js
src/handlers/index.js
src/handlers/town/townEnter.handler.js
src/utils/log/printPacket.js
src/utils/packet/makePacket.js
src/utils/packet/payload.js

공동 작업자
Co-authored-by: ppiok-OwO <ppiok-OwO@users.noreply.github.com>
Co-authored-by: Nanoda <nanoda1802@users.noreply.github.com>

feat : 클라이언트 접속, fix : 빅엔디안 리틀엔디안 문제 해결

---

src/handlers/town/townEnter.handler.js

fix : 코드수정 단일 전송을 전체 전송으로 변경

---

src/events/onData.js
src/handlers/index.js
src/handlers/town/townEnter.handler.js
src/utils/error/customError.js
src/utils/error/errorCodes.js
src/utils/error/errorHandler.js
src/utils/log/printPacket.js
src/utils/packet/makePacket.js
src/utils/packet/packet.js

시스템 에러 발생시 클라이언트에 채팅 보내기
입장시 시스템 알림 보내기
에러 처리 구문 추가
Packet 모듈 추가

feat: error handler

---

src/handlers/social/playerAnimation.handler.js
src/handlers/social/playerChat.handler.js

feat: 감정 표현 기능에 [시스템] 메시지 적용

---

src/config/config.js
src/events/onData.js
src/utils/error/errorHandler.js
src/utils/log/printPacket.js
src/utils/packet/makePacket.js

let을 const로 변경, try-catch를 함수로 변경(변수 재할당 방지)
packetTypeName 읽기 위한 config.packetId의 Entries를 최초 한번 저장
에러핸들러 보완 작성

refactor: 코드 최적화

---

src/handlers/social/playerAnimation.handler.js
src/handlers/social/playerChat.handler.js

fix: 예외처리 추가

---

src/handlers/gathering/StartGathering.handler.js
src/handlers/social/party/leaveParty.handler.js
src/utils/packet/payloadData.js

bugfix: 잘못된 메서드 수정

---

src/classes/party.class.js
src/classes/player.class.js
src/handlers/social/party/allowInvite.handler.js
src/handlers/social/party/createParty.handler.js
src/handlers/social/party/inviteParty.handler.js
src/handlers/social/party/joinParty.handler.js
src/handlers/social/party/kickOutParty.handler.js
src/handlers/social/party/leaveParty.handler.js
src/handlers/social/playerAnimation.handler.js
src/handlers/social/playerChat.handler.js

- player 인스턴스의 isInParty 속성을 삭제한 대신 partyId를 부여하였습니다.
- 이제 파티 조회 및 참가가 가능합니다.

feat: 파티 참가 기능 구현

---

src/handlers/account/createCharacter.handler.js
src/handlers/player/statUpdate.handler.js

원인 : createCharacter.handler에서 addPlayer를 중복 생성하고 있었습니다.
해결 : townEnter.handler에서만 addPlayer가 발생하도록 수정했습니다.

Fix : createCharacter Error 해결

---

src/handlers/social/party/kickOutParty.handler.js
src/handlers/social/party/leaveParty.handler.js
src/handlers/town/moveSectorHandler.js

파티에서 리터럴 관련 문제 해결 및 movesectorhandler 내용 수정

fix: movesectorhandler

---

.gitignore
src/classes/session/playerSession.class.js
src/classes/session/userSession.class.js
src/events/onEnd.js
src/handlers/town/moveSectorHandler.js

user 삭제시 player 삭제
player 삭제시 party, sector에서 삭제

feat: onEnd 종료시 user 삭제 및 user, player 삭제시 연결된 세션 동기화.

---

src/classes/session/redisSession.class.js
src/classes/session/userSession.class.js
src/db/user/user.db.js
src/db/user/user.queries.js
src/handlers/index.js
src/handlers/player/inventory/inventoryManager.js
src/handlers/ranking/ranking.handler.js
src/handlers/town/townEnter.handler.js
src/utils/error/errorHandler.js

- 처음 캐릭터를 생성했을 때 인벤토리에 아이템이 획득되지 않던 현상을 수정했습니다.
- Redis Session 데이터에 currentSector에 임시 데이터가 들어가 있던 부분을 이제는 sectorCode가 들어가게 됩니다.

Feat : 인벤토리 버그 수정 및 Redis Sector 데이터 추가

---

src/config/config.js
src/events/blacklist.js
src/events/onConnection.js
src/events/onData.js
src/events/onEnd.js

- 너무 빈번한 요청이 발생한 경우 용의자 리스트에 추가됩니다.(IP 차단 X)
- 잘못된 크기의 패킷이 도착한 경우 블랙 리스트에 추가됩니다.(IP 차단 O)
- 잘못된 형식의 패킷이 도착한 경우 블랙 리스트에 추가됩니다.(IP 차단 O)

어뷰저를 감지하여 IP 블랙리스트 기능 추가

---

src/classes/monster.class.js
src/classes/player.class.js
src/handlers/account/login.handler.js
src/handlers/playerAction/portal.handler.js
src/handlers/transport/moveSectorHandler.js
src/handlers/transport/playerLocationUpdate.handler.js

- 0.1초당 이동한 좌표를 받고 있다고 생각했으나, 생각해보니 0.1만큼의 거리를 이동할 때마다 패킷을 받고 있었습니다.
- 따라서 직전 좌표와의 차이가 0.1+offset(=>0.1로 설정)보다 크면 속도 검증 실패 로그를 출력하도록 변경하였습니다.
- 클라이언트가 민감하게 패킷을 보내는 건 아닌 건지, 꽤 실패가 자주 뜨긴 하네요

속도 검증 고쳤습니다.

---

src/constants/UpdateLocation.js
src/events/blacklist.js
src/events/onData.js
src/handlers/transport/playerLocationUpdate.handler.js
src/init/navMeshLoader.js

- 기존 5회에서 10회로 완화했습니다.
- 로컬에서 테스트할 때는 블랙리스트에 오르지 않습니다.
- 혹시 블랙리스트에 올라가신다면 어떤 콘솔이 찍히고 추가가 되었는지 캡쳐 부탁드립니다.(코드 수정에 큰 도움이 됩니다.)

블랙 리스트 기준 완화

---

src/events/onConnection.js
src/handlers/social/playerChat.handler.js

연결되면 socket으로 S2CChat 패킷 보내기 (타입:Auth)
C2SChat (타입:Auth) 받으면 socket.isUnity = true
1초 후에 socket.isUnity가 false면 socket.destroy()

feat : 연결하면 Auth 패킷 주고받기

---

src/constants/UpdateLocation.js
src/events/onConnection.js
src/handlers/social/playerChat.handler.js
src/handlers/transport/playerLocationUpdate.handler.js

- 소켓 연결 시 auth 작업을 잠시 비활성화 했습니다. 
- 속도와 위치 검증을 좀 더 널널하게 완화했습니다.(클라와 완벽하게 같은 경로를 연산하지 않기에)

feat: 속도 검증, 위치 검증 좀 더 널널하게

---

assets/furniture_recipe.json
src/handlers/ranking/ranking.handler.js

- 패킷을 너무 많이 사용하기 전송하기 때문에 ALL은 제외했습니다.

Feat : 랭킹 ALL 삭제, TOP 10, 20, 30 추가

---

src/handlers/player/inventory/craftEnd.handler.js

제작 완료시 모든 슬롯 순회하며 제작템 을 추가 -> 처음 한번만 추가함

fix : 제작 완료 핸들러 수정

---

src/handlers/transport/playerLocationUpdate.handler.js

if (player.isRunning || **player.usePortal**) {
serverDistance =
player.getMoveSpeed() * (elapsedTime / 1000) * 1.5 +
config.updateLocation.tolerance;
}

bugfix: 포탈 사용 시 속도 검증 예외 처리 추가

---

src/config/config.js
src/constants/header.js
src/handlers/index.js
src/handlers/transport/playerLocationUpdate.handler.js
src/handlers/transport/playerSpawnNotification.handler.js
src/protobuf/Protocol.proto
src/protobuf/packetNames.js
src/server.js

1. LocationUpdate 본인 제외하고 보내도록 변경
2. 클라에서  S2CLocationUpdate 받았는데 유저 없으면 C2SSpawn 보내서 스폰 요청함

동시 MoveSector 문제 개선?

---

src/server.js

미처리 에러로 서버가 종료되면 5초 간격 저장이 되지 않으므로
바로 저장하게 수정

fix : 미처리 에러는 바로 저장하게 수정
